const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Camera3D,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{DarAVolta: 0},
	{Projétil: 0},
	{fundo: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Senóide: 0},
	{Sprite: 0},
	{faseCompleta: 0},
	{Mouse: 0},
	{RestritoAoLayout: 0},
	{"8Direções": 0},
	{Plataforma: 0},
	{Sprite2: 0},
	{Teclado: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{vidas: 0},
	{Áudio: 0},
	{Toque: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Câmera3D: 0},
	{Sprite7: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{textoFase2: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{EntradaDeTexto: 0},
	{vidasdafase2: 0},
	{tempo: 0},
	{invencivel: 0}
];

self.InstanceType = {
	fundo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	faseCompleta: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	vidas: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Câmera3D: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	textoFase2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	vidasdafase2: class extends self.ITextInstance {}
}